#define _SHPDATA_										// important

#include <mgapiall.h>
#include "shpcode.h"
#include "shptable_.h"								// generated by ddbuild */
#include "shapes.h"

mgDeclarePlugin(
	"Shape Builders",									// vendor
	"Shapes Data Dictionary",						// name
	"6b109530-2567-11d2-90b5-006008a37a65"		// uuid
	);

#define ShpDataVersion "1.0"

/*----------------------------------------------------------------------------*\
	Data Dictionary Init
\*----------------------------------------------------------------------------*/


static mgplugintool PluginSite = MG_NULL;

MGPIDECLARE(mgbool) mgpInit ( mgplugin plugin, int* argc, char* argv [] )
{
	PluginSite = mgRegisterSite (
						plugin, 
						SHP_SITEID, 
						&RecordDefTable[0], 
						ShpRecordCodeMap, 
						SHPOP_RECORD_OFFSET, 
						SHP_RECORD_MAX,
						&DataDefTable[0], 
						ShpDataCodeMap, 
						SHPOP_DATA_OFFSET, 
						SHP_DATA_MAX,
						MTA_VERSION, ShpDataVersion, 
						MG_NULL );

	if (PluginSite) {
		InitActions (PluginSite);
		InitHelpers (PluginSite);
		InitDrawCallbacks (PluginSite);
	}

	return (PluginSite ? MG_TRUE : MG_FALSE);
}

MGPIDECLARE(void) mgpExit ( mgplugin plugin )
{
	ExitHelpers (PluginSite);
	ExitDrawCallbacks (PluginSite);
	mgUnregisterAllTools ( plugin );
}

