//-------------------------------------------------------------------------------
// $Revision: 1.2 $
// $Date: 2005/07/28 01:24:53 $
//-------------------------------------------------------------------------------
// Sample Plugin: MyData Data Extension
//
// Overview:
//	   This plugin registers a data extension site that extends OpenFlight.
// 
// API Functionality:
//		Data Extension
//       New Node Types (stand-alone extensions)
//       Extension Record Types (tag-along extensions)
//-------------------------------------------------------------------------------

#define _MYDATA_				/* important! */

#include <mgapiall.h>
#include "mycode.h"
#include "mytable_.h"		/* generated by ddbuild */

mgDeclarePlugin(
	"My Company",										// vendor
	"MyData Data Dictionary",						// name
	"5e2b23d0-1afe-11d1-9c7c-00a0241a8c3a"		// uuid
	);

#define MyDataVersion "1.0"

/*----------------------------------------------------------------------------*\
	Data Dictionary Init
\*----------------------------------------------------------------------------*/

extern void InitActions ( mgpluginsite pluginSite );
extern void InitHelpers ( mgpluginsite pluginSite );

MGPIDECLARE(mgbool) mgpInit ( mgplugin plugin, int* argc, char* argv [] )
{
	mgpluginsite pluginSite;

	pluginSite = mgRegisterSite (
						plugin, 
						"MYDATA", 
						&RecordDefTable[0], 
						MyRecordCodeMap, 
						MYOP_RECORD_OFFSET, 
						MY_RECORD_MAX,
						&DataDefTable[0], 
						MyDataCodeMap, 
						MYOP_DATA_OFFSET, 
						MY_DATA_MAX,
						MTA_VERSION, MyDataVersion, 
						MG_NULL );

	if (pluginSite) {
		InitActions (pluginSite);
		InitHelpers (pluginSite);
	}

	return (pluginSite ? MG_TRUE : MG_FALSE);
}

MGPIDECLARE(void) mgpExit ( mgplugin plugin )
{
	mgUnregisterAllTools ( plugin );
}

/*eof*/
